package DSLTrans.behavior;

/*Generated by MPS */

import transfverif.core.behavior.AbstractApplier_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ApplyModel_BehaviorDescriptor extends AbstractApplier_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "DSLTrans.structure.ApplyModel";
  }

}
