package DSLTrans.behavior;

/*Generated by MPS */

import transfverif.core.behavior.ApplyLink_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class IndirectApplyLink_BehaviorDescriptor extends ApplyLink_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "DSLTrans.structure.IndirectApplyLink";
  }

}
