package transfverif.core.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class DirectMatchLink_Constraints extends BaseConstraintsDescriptor {
  public DirectMatchLink_Constraints() {
    super(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x352209af6691d74fL));
  }
}
