package transfverif.core.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class ApplyAttributeString_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_c5pi1i_a(editorContext, node);
  }
  private EditorCell createCollection_c5pi1i_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_c5pi1i_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_c5pi1i_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_c5pi1i_b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_c5pi1i_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "(String)");
    editorCell.setCellId("Constant_c5pi1i_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_c5pi1i_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new ApplyAttributeString_Editor.atomSingleRoleHandler_c5pi1i_b0(node, MetaAdapterFactory.getContainmentLink(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x61d4bac5f384b661L, 0x61d4bac5f384b667L, "atom"), editorContext);
    return provider.createCell();
  }
  private class atomSingleRoleHandler_c5pi1i_b0 extends SingleRoleCellProvider {
    public atomSingleRoleHandler_c5pi1i_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("atom");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_atom");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no atom>";
    }
  }
}
