package SyVOLT.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAndContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.AndContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334dbL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "SyVOLT.structure.BinaryContractFormula").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d5L)).create();
  /*package*/ final ConceptDescriptor myConceptAtomicContract = new ConceptDescriptorBuilder("SyVOLT.structure.AtomicContract", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x61d4bac5f384b8b9L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "SyVOLT.structure.ContractFormula").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L)).childDescriptors(new ConceptDescriptorBuilder.Link(4439542802417895567L, "preCondition", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca83742c88dL), true, false, false), new ConceptDescriptorBuilder.Link(4439542802417895569L, "postCondition", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca83742c88eL), true, false, false), new ConceptDescriptorBuilder.Link(4439542802417895572L, "traceLinks", MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x352209af6691d76dL), true, true, false)).children(new String[]{"preCondition", "postCondition", "traceLinks"}, new boolean[]{false, false, true}).create();
  /*package*/ final ConceptDescriptor myConceptBinaryContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.BinaryContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d5L)).interface_().parents("SyVOLT.structure.ContractFormula").parentIds(MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4439542802417923305L, "arg1", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L), false), new ConceptDescriptorBuilder.Ref(4439542802417923309L, "arg2", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L), false)).references("arg1", "arg2").create();
  /*package*/ final ConceptDescriptor myConceptContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.ContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L)).interface_().parents("jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptContractSet = new ConceptDescriptorBuilder("SyVOLT.structure.ContractSet", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x61d4bac5f384b8b8L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4439542802417930852L, "inputLanguage"), new ConceptDescriptorBuilder.Prop(4439542802417930854L, "outputLanguage")).properties("inputLanguage", "outputLanguage").childDescriptors(new ConceptDescriptorBuilder.Link(7049464676098554042L, "contracts", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x61d4bac5f384b8b9L), true, true, false), new ConceptDescriptorBuilder.Link(4439542802417923314L, "formulae", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L), true, true, false), new ConceptDescriptorBuilder.Link(4439542802417929364L, "sameElements", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca837434c98L), true, true, false)).children(new String[]{"contracts", "formulae", "sameElements"}, new boolean[]{true, true, true}).create();
  /*package*/ final ConceptDescriptor myConceptImplicationContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.ImplicationContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334e3L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "SyVOLT.structure.BinaryContractFormula").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d5L)).create();
  /*package*/ final ConceptDescriptor myConceptIndirectApplyLink = new ConceptDescriptorBuilder("SyVOLT.structure.IndirectApplyLink", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca83742c89bL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "transfverif.core.structure.ApplyLink").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x3d9c6ca83742c8a8L)).alias("Indirect Apply", "").create();
  /*package*/ final ConceptDescriptor myConceptNotContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.NotContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334e6L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "SyVOLT.structure.UnaryContractFormula").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d8L)).create();
  /*package*/ final ConceptDescriptor myConceptOrContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.OrContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334deL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "SyVOLT.structure.BinaryContractFormula").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d5L)).create();
  /*package*/ final ConceptDescriptor myConceptPostCondition = new ConceptDescriptorBuilder("SyVOLT.structure.PostCondition", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca83742c88eL)).super_("transfverif.core.structure.AbstractApplier").super_(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x352209af6691d6e3L)).parents("transfverif.core.structure.AbstractApplier").parentIds(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x352209af6691d6e3L)).create();
  /*package*/ final ConceptDescriptor myConceptPreCondition = new ConceptDescriptorBuilder("SyVOLT.structure.PreCondition", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca83742c88dL)).super_("transfverif.core.structure.AbstractMatcher").super_(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x61d4bac5f384b645L)).parents("transfverif.core.structure.AbstractMatcher").parentIds(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x61d4bac5f384b645L)).create();
  /*package*/ final ConceptDescriptor myConceptSameElement = new ConceptDescriptorBuilder("SyVOLT.structure.SameElement", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca837434c98L)).interface_().create();
  /*package*/ final ConceptDescriptor myConceptSamePostElement = new ConceptDescriptorBuilder("SyVOLT.structure.SamePostElement", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca837433cdaL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "transfverif.core.structure.ApplyLink", "SyVOLT.structure.SameElement").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x3d9c6ca83742c8a8L), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca837434c98L)).alias("Same Post Element", "").create();
  /*package*/ final ConceptDescriptor myConceptSamePreElement = new ConceptDescriptorBuilder("SyVOLT.structure.SamePreElement", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334f5L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "transfverif.core.structure.MatchLink", "SyVOLT.structure.SameElement").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x26ce87c265488de4L), MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca837434c98L)).alias("Same Pre Element", "").create();
  /*package*/ final ConceptDescriptor myConceptUnaryContractFormula = new ConceptDescriptorBuilder("SyVOLT.structure.UnaryContractFormula", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d8L)).interface_().parents("SyVOLT.structure.ContractFormula").parentIds(MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4439542802417923312L, "arg", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3d9c6ca8374334d4L), false)).references("arg").create();
  /*package*/ final ConceptDescriptor myConceptWildcard = new ConceptDescriptorBuilder("SyVOLT.structure.Wildcard", MetaIdFactory.conceptId(0x69eded0a1bc3427eL, 0x9a48e8713d355d49L, 0x3e9562919593320bL)).super_("transfverif.core.structure.ApplyAttributeValue").super_(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x61d4bac5f384b675L)).parents("transfverif.core.structure.ApplyAttributeValue").parentIds(MetaIdFactory.conceptId(0xa2c7a1ebb3b54bbbL, 0x819be25a3c6de3a8L, 0x61d4bac5f384b675L)).alias("Wildcard", "").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAndContractFormula, myConceptAtomicContract, myConceptBinaryContractFormula, myConceptContractFormula, myConceptContractSet, myConceptImplicationContractFormula, myConceptIndirectApplyLink, myConceptNotContractFormula, myConceptOrContractFormula, myConceptPostCondition, myConceptPreCondition, myConceptSameElement, myConceptSamePostElement, myConceptSamePreElement, myConceptUnaryContractFormula, myConceptWildcard);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0u, conceptFqName)) {
      case 0:
        return myConceptAndContractFormula;
      case 1:
        return myConceptAtomicContract;
      case 2:
        return myConceptBinaryContractFormula;
      case 3:
        return myConceptContractFormula;
      case 4:
        return myConceptContractSet;
      case 5:
        return myConceptImplicationContractFormula;
      case 6:
        return myConceptIndirectApplyLink;
      case 7:
        return myConceptNotContractFormula;
      case 8:
        return myConceptOrContractFormula;
      case 9:
        return myConceptPostCondition;
      case 10:
        return myConceptPreCondition;
      case 11:
        return myConceptSameElement;
      case 12:
        return myConceptSamePostElement;
      case 13:
        return myConceptSamePreElement;
      case 14:
        return myConceptUnaryContractFormula;
      case 15:
        return myConceptWildcard;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0u = new String[]{"SyVOLT.structure.AndContractFormula", "SyVOLT.structure.AtomicContract", "SyVOLT.structure.BinaryContractFormula", "SyVOLT.structure.ContractFormula", "SyVOLT.structure.ContractSet", "SyVOLT.structure.ImplicationContractFormula", "SyVOLT.structure.IndirectApplyLink", "SyVOLT.structure.NotContractFormula", "SyVOLT.structure.OrContractFormula", "SyVOLT.structure.PostCondition", "SyVOLT.structure.PreCondition", "SyVOLT.structure.SameElement", "SyVOLT.structure.SamePostElement", "SyVOLT.structure.SamePreElement", "SyVOLT.structure.UnaryContractFormula", "SyVOLT.structure.Wildcard"};
}
